apiVersion: skaffold/v3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
deploy:
  kubectl:
    {}
build:
  local:
    push: false
  artifacts:
    - image: auth
      context: ./auth
      docker:
        dockerfile: Dockerfile