apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: orders
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
          - name: MONGO_URI
            value: 'mongodb://orders-mongo-srv:27017/auth'
          - name: JWT_KEY
            valueFrom:
              secretKeyRef:
                name: jwt-secret
                key: JWT_KEY
          - name: EVENT_BUS_HOST
            value: 'event-bus-srv'
          - name: EVENT_BUS_PORT
            value: '5672'
          - name: EVENT_BUS_USERNAME
            value: 'eventbus'
          - name: EVENT_BUS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: event-bus-password
                key: EVENT_BUS_PASSWORD

---
apiVersion: v1
kind: Service
metadata:
  name: orders-srv
spec:
  selector:
    app: orders
  ports:
  - name: orders
    protocol: TCP
    port: 3000
    targetPort: 3000
